name: AGM 24

on:
  push:
    branches:
      - master
      - unit-test

jobs:
  dev-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
      run: |
        echo "Environment: ${{ vars.ENVIRONMENT }}"

  staging-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment
      run: |
        echo "Environment: ${{ vars.ENVIRONMENT }}"